### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by LiztochekCode** [NuroDev/nuro.dev#66]
Types of parameters 'file' and 'file' are incompatible.
          Type 'VFile' is missing the following properties from type 'VFile': value, stored, result, map

  59 |          scope: data,
  60 |          mdxOptions: {
> 61 |                  rehypePlugins: [[RehypeAutolinkHeadings, {}]],
     |                                   ^
  62 |                  remarkPlugins: [RemarkCodeTitles, RemarkEmoji, RemarkPrism, RemarkSlug],
  63 |          },
  64 |  });

**Comment by LiztochekCode** [comment]
i fix this, but new error
> Build error occurred
Error: Export encountered errors on following paths:
        /blog/[slug]: /blog/hello_world
        /blog/[slug]: /blog/improving_next_config
        /blog/[slug]: /blog/using_github_as_a_cms
    at C:\likethis\nuro.dev\node_modules\next\dist\export\index.js:404:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (C:\likethis\nuro.dev\node_modules\next\dist\trace\trace.js:79:20)
    at async C:\likethis\nuro.dev\node_modules\next\dist\build\index.js:1230:21
    at async Span.traceAsyncFn (C:\likethis\nuro.dev\node_modules\next\dist\trace\trace.js:79:20)
    at async C:\likethis\nuro.dev\node_modules\next\dist\build\index.js:1092:17
    at async Span.traceAsyncFn (C:\likethis\nuro.dev\node_modules\next\dist\trace\trace.js:79:20)
    at async Object.build [as default] (C:\likethis\nuro.dev\node_modules\next\dist\build\index.js:65:29)
